version: '3.8'

services:

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.fastapi
    ports:
      - 5000:5000
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000

  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
